{
  "openapi": "3.0.1",
  "info": {
    "title": "Default module",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [],
  "paths": {
    "/auth/login": {
      "post": {
        "summary": "login",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "email",
            "in": "query",
            "description": "",
            "required": false,
            "example": "admin@example.com",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "password",
            "in": "query",
            "description": "",
            "required": false,
            "example": "admin123",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "email": "sanjaya.slegy@gmail.com",
                "password": "asdfasdf"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "1": {
                    "summary": "Login",
                    "value": {
                      "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZTMyYzA2OS1jMzFmLTRhZjUtYjgxOC02NmYyYTBhOTk4OGIiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwicm9sZSI6InN1cGVyX2FkbWluIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzY3NjAxMzUzLCJleHAiOjE3NjgyMDYxNTN9.oJywbn7_8y1JkbGVXC1XAxwTRZxHXHmkX0-h4vgSRpc"
                    }
                  },
                  "2": {
                    "summary": "Success",
                    "value": {
                      "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZTMyYzA2OS1jMzFmLTRhZjUtYjgxOC02NmYyYTBhOTk4OGIiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwicm9sZSI6InN1cGVyX2FkbWluIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzY3NjAxMzUzLCJleHAiOjE3NjgyMDYxNTN9.oJywbn7_8y1JkbGVXC1XAxwTRZxHXHmkX0-h4vgSRpc"
                    }
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/auth/profile": {
      "get": {
        "summary": "profile",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer {{token}}",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "examples": {}
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "id": "9e32c069-c31f-4af5-b818-66f2a0a9988b",
                  "firstName": "Super",
                  "lastName": "Admin",
                  "email": "admin@example.com",
                  "isActive": true,
                  "createdAt": "2026-01-05T06:24:36.713Z",
                  "updatedAt": "2026-01-05T06:24:36.713Z",
                  "role": {
                    "id": "122642be-f582-488c-a14d-3e4bf454d5df",
                    "name": "super_admin",
                    "description": "System super administrator",
                    "isAdmin": true,
                    "permissions": [
                      {
                        "name": "User Management",
                        "read": true,
                        "write": true,
                        "delete": true
                      },
                      {
                        "name": "Roles and Permission",
                        "read": true,
                        "write": true,
                        "delete": true
                      },
                      {
                        "name": "Group and Teams",
                        "read": true,
                        "write": true,
                        "delete": true
                      },
                      {
                        "name": "User Invitation",
                        "read": true,
                        "write": true,
                        "delete": true
                      },
                      {
                        "name": "Project",
                        "read": true,
                        "write": true,
                        "delete": true
                      },
                      {
                        "name": "Project Settings",
                        "read": true,
                        "write": true,
                        "delete": true
                      },
                      {
                        "name": "Task Manager",
                        "read": true,
                        "write": true,
                        "delete": true
                      },
                      {
                        "name": "Task Assignment",
                        "read": true,
                        "write": true,
                        "delete": true
                      },
                      {
                        "name": "Workflow Configuration",
                        "read": true,
                        "write": true,
                        "delete": true
                      }
                    ],
                    "createdAt": "2026-01-05T06:07:32.426Z",
                    "updatedAt": "2026-01-05T06:07:32.426Z"
                  },
                  "resetToken": null,
                  "resetTokenExpires": null
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "patch": {
        "summary": "Update Profile",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer {{token}}",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "firstName": "Jhon",
                "lastName": "Due"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "id": "8eb7a733-ad3e-467a-aa4c-2885b3cdfbc0",
                  "firstName": "Jhon",
                  "lastName": "Due",
                  "phone": null,
                  "organization": null,
                  "avatar": null,
                  "roleId": "122642be-f582-488c-a14d-3e4bf454d5df",
                  "isActive": true,
                  "createdAt": "2026-01-06T05:52:32.278Z",
                  "updatedAt": "2026-01-06T05:52:32.278Z",
                  "role": {
                    "id": "122642be-f582-488c-a14d-3e4bf454d5df",
                    "name": "super_admin",
                    "description": "System super administrator",
                    "isAdmin": true,
                    "permissions": [
                      {
                        "name": "User Management",
                        "read": true,
                        "write": true,
                        "delete": true
                      },
                      {
                        "name": "Roles and Permission",
                        "read": true,
                        "write": true,
                        "delete": true
                      },
                      {
                        "name": "Group and Teams",
                        "read": true,
                        "write": true,
                        "delete": true
                      },
                      {
                        "name": "User Invitation",
                        "read": true,
                        "write": true,
                        "delete": true
                      },
                      {
                        "name": "Project",
                        "read": true,
                        "write": true,
                        "delete": true
                      },
                      {
                        "name": "Project Settings",
                        "read": true,
                        "write": true,
                        "delete": true
                      },
                      {
                        "name": "Task Manager",
                        "read": true,
                        "write": true,
                        "delete": true
                      },
                      {
                        "name": "Task Assignment",
                        "read": true,
                        "write": true,
                        "delete": true
                      },
                      {
                        "name": "Workflow Configuration",
                        "read": true,
                        "write": true,
                        "delete": true
                      }
                    ],
                    "createdAt": "2026-01-05T06:07:32.426Z",
                    "updatedAt": "2026-01-05T06:07:32.426Z"
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/auth/forgot-password": {
      "post": {
        "summary": "forgot-password",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "email": "sanjaya.slegy@gmail.com"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "message": "If that account exists, a reset email has been sent."
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/auth/reset-password": {
      "post": {
        "summary": "reset-password",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "email": "sanjaya.slegy@gmail.com",
                "token": "761676f23d45be75fac8c86a62e0bbcecd37917bef61b987eb23f5275c43056c",
                "password": "newpassword",
                "confirmPassword": "newpassword"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "1": {
                    "summary": "reset-password",
                    "value": {
                      "message": "Password updated successfully"
                    }
                  },
                  "2": {
                    "summary": "Exception",
                    "value": {
                      "statusCode": 400,
                      "message": "Invalid or expired reset token"
                    }
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/auth/logout": {
      "post": {
        "summary": "logout",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer {{token}}",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "message": "Logged out successfully"
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/auth/change-password": {
      "post": {
        "summary": "Change Password",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer {{token}}",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "currentPassword": "newpassword",
                "newPassword": "asdfasdf",
                "confirmPassword": "asdfasdf"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "1": {
                    "summary": "Bad Request",
                    "value": {
                      "statusCode": 400,
                      "message": "Expected property name or '}' in JSON at position 6 (line 2 column 5)"
                    }
                  },
                  "2": {
                    "summary": "Success",
                    "value": {
                      "message": "Password changed successfully"
                    }
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/auth/google": {
      "get": {
        "summary": "Login with google",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "1": {
                    "summary": "Login",
                    "value": {
                      "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZTMyYzA2OS1jMzFmLTRhZjUtYjgxOC02NmYyYTBhOTk4OGIiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwicm9sZSI6InN1cGVyX2FkbWluIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzY3NjAxMzUzLCJleHAiOjE3NjgyMDYxNTN9.oJywbn7_8y1JkbGVXC1XAxwTRZxHXHmkX0-h4vgSRpc"
                    }
                  },
                  "2": {
                    "summary": "Success",
                    "value": {
                      "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZTMyYzA2OS1jMzFmLTRhZjUtYjgxOC02NmYyYTBhOTk4OGIiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwicm9sZSI6InN1cGVyX2FkbWluIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzY3NjAxMzUzLCJleHAiOjE3NjgyMDYxNTN9.oJywbn7_8y1JkbGVXC1XAxwTRZxHXHmkX0-h4vgSRpc"
                    }
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/auth/microsoft": {
      "get": {
        "summary": "Login with Microsoft",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "1": {
                    "summary": "Login",
                    "value": {
                      "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZTMyYzA2OS1jMzFmLTRhZjUtYjgxOC02NmYyYTBhOTk4OGIiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwicm9sZSI6InN1cGVyX2FkbWluIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzY3NjAxMzUzLCJleHAiOjE3NjgyMDYxNTN9.oJywbn7_8y1JkbGVXC1XAxwTRZxHXHmkX0-h4vgSRpc"
                    }
                  },
                  "2": {
                    "summary": "Success",
                    "value": {
                      "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZTMyYzA2OS1jMzFmLTRhZjUtYjgxOC02NmYyYTBhOTk4OGIiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwicm9sZSI6InN1cGVyX2FkbWluIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzY3NjAxMzUzLCJleHAiOjE3NjgyMDYxNTN9.oJywbn7_8y1JkbGVXC1XAxwTRZxHXHmkX0-h4vgSRpc"
                    }
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    }
  },
  "components": {
    "schemas": {},
    "responses": {},
    "securitySchemes": {}
  },
  "servers": [],
  "security": []
}