{
  "openapi": "3.0.1",
  "info": {
    "title": "Default module",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [],
  "paths": {
    "/groups": {
      "post": {
        "summary": "Create",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer {{token}}",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "name": "Group q",
                "description": "This is test groups"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "1": {
                    "summary": "Bad Request",
                    "value": {
                      "statusCode": 400,
                      "message": "Validation failed"
                    }
                  },
                  "2": {
                    "summary": "Success",
                    "value": {
                      "message": "Group created successfully",
                      "group": {
                        "name": "Group 1",
                        "description": "This is test groups",
                        "id": "aa0b1a79-a196-4240-8b29-fc3c5c0bcbdf",
                        "createdAt": "2026-01-07T08:46:10.704Z",
                        "updatedAt": "2026-01-07T08:46:10.704Z",
                        "totalMembers": 0
                      }
                    }
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "get": {
        "summary": "Find All",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "description": "",
            "required": false,
            "example": "1",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "limit",
            "in": "query",
            "description": "",
            "required": false,
            "example": "10",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "keywords",
            "in": "query",
            "description": "",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer {{token}}",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": ""
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "1": {
                    "summary": "Bad Request",
                    "value": {
                      "statusCode": 400,
                      "message": "Validation failed"
                    }
                  },
                  "2": {
                    "summary": "Success",
                    "value": {
                      "message": "Group created successfully",
                      "group": {
                        "name": "Group 1",
                        "description": "This is test groups",
                        "id": "aa0b1a79-a196-4240-8b29-fc3c5c0bcbdf",
                        "createdAt": "2026-01-07T08:46:10.704Z",
                        "updatedAt": "2026-01-07T08:46:10.704Z",
                        "totalMembers": 0
                      }
                    }
                  },
                  "3": {
                    "summary": "Success",
                    "value": {
                      "id": "aa0b1a79-a196-4240-8b29-fc3c5c0bcbdf",
                      "name": "Group 1",
                      "description": "This is test groups",
                      "createdAt": "2026-01-07T08:46:10.704Z",
                      "updatedAt": "2026-01-07T08:46:10.704Z",
                      "totalMembers": 0,
                      "users": []
                    }
                  },
                  "4": {
                    "summary": "Success",
                    "value": {
                      "data": [
                        {
                          "id": "aa0b1a79-a196-4240-8b29-fc3c5c0bcbdf",
                          "name": "Group 1",
                          "description": "This is test groups",
                          "createdAt": "2026-01-07T08:46:10.704Z",
                          "updatedAt": "2026-01-07T08:46:10.704Z",
                          "users": [
                            {
                              "id": "e9826307-afe5-42be-ae2a-866489ba95c5",
                              "firstName": "Test",
                              "lastName": "Jaya",
                              "email": "testaja@mail.com",
                              "phone": "98782937",
                              "language": "no",
                              "organization": "Lomedia",
                              "avatar": null,
                              "roleId": "742eaeac-1de0-4a50-a337-e75326ceb502",
                              "isActive": false,
                              "customValues": {
                                "unit": 34,
                                "salary": 30000,
                                "born-date": "2025-10-12",
                                "select-this": "Baso"
                              },
                              "createdAt": "2026-01-07T05:29:13.156Z",
                              "updatedAt": "2026-01-07T05:29:13.156Z"
                            },
                            {
                              "id": "b1dc2f22-4e4a-49fe-bfec-9607f5a00e76",
                              "firstName": "Test aja ges",
                              "lastName": "Jaya ad",
                              "email": "testaja2@mail.com",
                              "phone": "98782937",
                              "language": "no",
                              "organization": "Lomedia",
                              "avatar": null,
                              "roleId": "742eaeac-1de0-4a50-a337-e75326ceb502",
                              "isActive": false,
                              "customValues": {
                                "unit": 34,
                                "salary": 30000,
                                "born-date": "2025-10-12",
                                "select-this": "Siomay"
                              },
                              "createdAt": "2026-01-07T05:44:41.836Z",
                              "updatedAt": "2026-01-07T05:44:41.836Z"
                            }
                          ],
                          "totalMembers": 2
                        }
                      ],
                      "meta": {
                        "itemsPerPage": 10,
                        "totalItems": 1,
                        "currentPage": 1,
                        "totalPages": 1,
                        "sortBy": [
                          [
                            "createdAt",
                            "DESC"
                          ]
                        ]
                      },
                      "links": {
                        "current": "http://localhost:3333/users/groups?page=1&limit=10&sortBy=createdAt:DESC"
                      }
                    }
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/groups/{id}": {
      "get": {
        "summary": "Find One",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "example": "aa0b1a79-a196-4240-8b29-fc3c5c0bcbdf",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer {{token}}",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": ""
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "1": {
                    "summary": "Bad Request",
                    "value": {
                      "statusCode": 400,
                      "message": "Validation failed"
                    }
                  },
                  "2": {
                    "summary": "Success",
                    "value": {
                      "message": "Group created successfully",
                      "group": {
                        "name": "Group 1",
                        "description": "This is test groups",
                        "id": "aa0b1a79-a196-4240-8b29-fc3c5c0bcbdf",
                        "createdAt": "2026-01-07T08:46:10.704Z",
                        "updatedAt": "2026-01-07T08:46:10.704Z",
                        "totalMembers": 0
                      }
                    }
                  },
                  "3": {
                    "summary": "Success",
                    "value": {
                      "id": "aa0b1a79-a196-4240-8b29-fc3c5c0bcbdf",
                      "name": "Group 1",
                      "description": "This is test groups",
                      "createdAt": "2026-01-07T08:46:10.704Z",
                      "updatedAt": "2026-01-07T08:46:10.704Z",
                      "totalMembers": 0,
                      "users": []
                    }
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "patch": {
        "summary": "Update",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "example": "aa0b1a79-a196-4240-8b29-fc3c5c0bcbdf",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer {{token}}",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "name": "Modify",
                "description": ""
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "1": {
                    "summary": "Bad Request",
                    "value": {
                      "statusCode": 400,
                      "message": "Validation failed"
                    }
                  },
                  "2": {
                    "summary": "Success",
                    "value": {
                      "message": "Group created successfully",
                      "group": {
                        "name": "Group 1",
                        "description": "This is test groups",
                        "id": "aa0b1a79-a196-4240-8b29-fc3c5c0bcbdf",
                        "createdAt": "2026-01-07T08:46:10.704Z",
                        "updatedAt": "2026-01-07T08:46:10.704Z",
                        "totalMembers": 0
                      }
                    }
                  },
                  "3": {
                    "summary": "Success",
                    "value": {
                      "id": "aa0b1a79-a196-4240-8b29-fc3c5c0bcbdf",
                      "name": "Group 1",
                      "description": "This is test groups",
                      "createdAt": "2026-01-07T08:46:10.704Z",
                      "updatedAt": "2026-01-07T08:46:10.704Z",
                      "totalMembers": 0,
                      "users": []
                    }
                  },
                  "4": {
                    "summary": "Success",
                    "value": {
                      "message": "Users added to group",
                      "group": {
                        "id": "aa0b1a79-a196-4240-8b29-fc3c5c0bcbdf",
                        "name": "Group 1",
                        "description": "This is test groups",
                        "createdAt": "2026-01-07T08:46:10.704Z",
                        "updatedAt": "2026-01-07T08:46:10.704Z",
                        "totalMembers": 2,
                        "users": [
                          {
                            "id": "e9826307-afe5-42be-ae2a-866489ba95c5",
                            "firstName": "Test",
                            "lastName": "Jaya",
                            "email": "testaja@mail.com",
                            "phone": "98782937",
                            "language": "no",
                            "organization": "Lomedia",
                            "avatar": null,
                            "roleId": "742eaeac-1de0-4a50-a337-e75326ceb502",
                            "isActive": false,
                            "customValues": {
                              "unit": 34,
                              "salary": 30000,
                              "born-date": "2025-10-12",
                              "select-this": "Baso"
                            },
                            "createdAt": "2026-01-07T05:29:13.156Z",
                            "updatedAt": "2026-01-07T05:29:13.156Z"
                          },
                          {
                            "id": "b1dc2f22-4e4a-49fe-bfec-9607f5a00e76",
                            "firstName": "Test aja ges",
                            "lastName": "Jaya ad",
                            "email": "testaja2@mail.com",
                            "phone": "98782937",
                            "language": "no",
                            "organization": "Lomedia",
                            "avatar": null,
                            "roleId": "742eaeac-1de0-4a50-a337-e75326ceb502",
                            "isActive": false,
                            "customValues": {
                              "unit": 34,
                              "salary": 30000,
                              "born-date": "2025-10-12",
                              "select-this": "Siomay"
                            },
                            "createdAt": "2026-01-07T05:44:41.836Z",
                            "updatedAt": "2026-01-07T05:44:41.836Z"
                          }
                        ]
                      }
                    }
                  },
                  "5": {
                    "summary": "Success",
                    "value": {
                      "groupId": "aa0b1a79-a196-4240-8b29-fc3c5c0bcbdf",
                      "totalMembers": 2,
                      "matched": 3,
                      "users": [
                        {
                          "id": "b1dc2f22-4e4a-49fe-bfec-9607f5a00e76",
                          "firstName": "Test aja ges",
                          "lastName": "Jaya ad",
                          "email": "testaja2@mail.com",
                          "phone": "98782937",
                          "language": "no",
                          "organization": "Lomedia",
                          "avatar": null,
                          "roleId": "742eaeac-1de0-4a50-a337-e75326ceb502",
                          "password": "$2b$10$1vmxBab3S0WZZ4Aw3kcSxeyOg6lAsKg1dRVvLrdREy.gzfpR6v.vS",
                          "isActive": false,
                          "customValues": {
                            "unit": 34,
                            "salary": 30000,
                            "born-date": "2025-10-12",
                            "select-this": "Siomay"
                          },
                          "createdAt": "2026-01-07T05:44:41.836Z",
                          "updatedAt": "2026-01-07T05:44:41.836Z",
                          "isJoined": true
                        },
                        {
                          "id": "e9826307-afe5-42be-ae2a-866489ba95c5",
                          "firstName": "Test",
                          "lastName": "Jaya",
                          "email": "testaja@mail.com",
                          "phone": "98782937",
                          "language": "no",
                          "organization": "Lomedia",
                          "avatar": null,
                          "roleId": "742eaeac-1de0-4a50-a337-e75326ceb502",
                          "password": "$2b$10$BL.FmTuct8CRtMdS3brj2uaUeSpjjEA2pt4mNxRepXbilwx9xy7YS",
                          "isActive": false,
                          "customValues": {
                            "unit": 34,
                            "salary": 30000,
                            "born-date": "2025-10-12",
                            "select-this": "Baso"
                          },
                          "createdAt": "2026-01-07T05:29:13.156Z",
                          "updatedAt": "2026-01-07T05:29:13.156Z",
                          "isJoined": true
                        },
                        {
                          "id": "89d444d0-d7e7-44a9-9d0d-2289f47a4bae",
                          "firstName": "Test",
                          "lastName": "Jaya",
                          "email": "test@mail.com",
                          "phone": "98782937",
                          "language": "no",
                          "organization": "Lomedia",
                          "avatar": null,
                          "roleId": "742eaeac-1de0-4a50-a337-e75326ceb502",
                          "password": "$2b$10$HPLneRACKasEBkSgxE/Ga.A1xpKPjd8VtR92m18e695LLzvs/n1Ju",
                          "isActive": false,
                          "customValues": {},
                          "createdAt": "2026-01-06T07:51:34.747Z",
                          "updatedAt": "2026-01-06T07:51:34.747Z",
                          "isJoined": false
                        }
                      ]
                    }
                  },
                  "6": {
                    "summary": "Success",
                    "value": {
                      "message": "Group updated successfully",
                      "group": {
                        "id": "aa0b1a79-a196-4240-8b29-fc3c5c0bcbdf",
                        "name": "Modify",
                        "description": "",
                        "createdAt": "2026-01-07T08:46:10.704Z",
                        "updatedAt": "2026-01-07T09:12:11.112Z",
                        "totalMembers": 2,
                        "users": [
                          {
                            "id": "e9826307-afe5-42be-ae2a-866489ba95c5",
                            "firstName": "Test",
                            "lastName": "Jaya",
                            "email": "testaja@mail.com",
                            "phone": "98782937",
                            "language": "no",
                            "organization": "Lomedia",
                            "avatar": null,
                            "roleId": "742eaeac-1de0-4a50-a337-e75326ceb502",
                            "isActive": false,
                            "customValues": {
                              "unit": 34,
                              "salary": 30000,
                              "born-date": "2025-10-12",
                              "select-this": "Baso"
                            },
                            "createdAt": "2026-01-07T05:29:13.156Z",
                            "updatedAt": "2026-01-07T05:29:13.156Z"
                          },
                          {
                            "id": "b1dc2f22-4e4a-49fe-bfec-9607f5a00e76",
                            "firstName": "Test aja ges",
                            "lastName": "Jaya ad",
                            "email": "testaja2@mail.com",
                            "phone": "98782937",
                            "language": "no",
                            "organization": "Lomedia",
                            "avatar": null,
                            "roleId": "742eaeac-1de0-4a50-a337-e75326ceb502",
                            "isActive": false,
                            "customValues": {
                              "unit": 34,
                              "salary": 30000,
                              "born-date": "2025-10-12",
                              "select-this": "Siomay"
                            },
                            "createdAt": "2026-01-07T05:44:41.836Z",
                            "updatedAt": "2026-01-07T05:44:41.836Z"
                          }
                        ]
                      }
                    }
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "delete": {
        "summary": "Delete",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "example": "0fc7140c-df3d-42db-9b94-f2711509f850",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer {{token}}",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": ""
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "1": {
                    "summary": "Bad Request",
                    "value": {
                      "statusCode": 400,
                      "message": "Validation failed"
                    }
                  },
                  "2": {
                    "summary": "Success",
                    "value": {
                      "message": "Group created successfully",
                      "group": {
                        "name": "Group 1",
                        "description": "This is test groups",
                        "id": "aa0b1a79-a196-4240-8b29-fc3c5c0bcbdf",
                        "createdAt": "2026-01-07T08:46:10.704Z",
                        "updatedAt": "2026-01-07T08:46:10.704Z",
                        "totalMembers": 0
                      }
                    }
                  },
                  "3": {
                    "summary": "Success",
                    "value": {
                      "id": "aa0b1a79-a196-4240-8b29-fc3c5c0bcbdf",
                      "name": "Group 1",
                      "description": "This is test groups",
                      "createdAt": "2026-01-07T08:46:10.704Z",
                      "updatedAt": "2026-01-07T08:46:10.704Z",
                      "totalMembers": 0,
                      "users": []
                    }
                  },
                  "4": {
                    "summary": "Success",
                    "value": {
                      "message": "Users added to group",
                      "group": {
                        "id": "aa0b1a79-a196-4240-8b29-fc3c5c0bcbdf",
                        "name": "Group 1",
                        "description": "This is test groups",
                        "createdAt": "2026-01-07T08:46:10.704Z",
                        "updatedAt": "2026-01-07T08:46:10.704Z",
                        "totalMembers": 2,
                        "users": [
                          {
                            "id": "e9826307-afe5-42be-ae2a-866489ba95c5",
                            "firstName": "Test",
                            "lastName": "Jaya",
                            "email": "testaja@mail.com",
                            "phone": "98782937",
                            "language": "no",
                            "organization": "Lomedia",
                            "avatar": null,
                            "roleId": "742eaeac-1de0-4a50-a337-e75326ceb502",
                            "isActive": false,
                            "customValues": {
                              "unit": 34,
                              "salary": 30000,
                              "born-date": "2025-10-12",
                              "select-this": "Baso"
                            },
                            "createdAt": "2026-01-07T05:29:13.156Z",
                            "updatedAt": "2026-01-07T05:29:13.156Z"
                          },
                          {
                            "id": "b1dc2f22-4e4a-49fe-bfec-9607f5a00e76",
                            "firstName": "Test aja ges",
                            "lastName": "Jaya ad",
                            "email": "testaja2@mail.com",
                            "phone": "98782937",
                            "language": "no",
                            "organization": "Lomedia",
                            "avatar": null,
                            "roleId": "742eaeac-1de0-4a50-a337-e75326ceb502",
                            "isActive": false,
                            "customValues": {
                              "unit": 34,
                              "salary": 30000,
                              "born-date": "2025-10-12",
                              "select-this": "Siomay"
                            },
                            "createdAt": "2026-01-07T05:44:41.836Z",
                            "updatedAt": "2026-01-07T05:44:41.836Z"
                          }
                        ]
                      }
                    }
                  },
                  "5": {
                    "summary": "Success",
                    "value": {
                      "groupId": "aa0b1a79-a196-4240-8b29-fc3c5c0bcbdf",
                      "totalMembers": 2,
                      "matched": 3,
                      "users": [
                        {
                          "id": "b1dc2f22-4e4a-49fe-bfec-9607f5a00e76",
                          "firstName": "Test aja ges",
                          "lastName": "Jaya ad",
                          "email": "testaja2@mail.com",
                          "phone": "98782937",
                          "language": "no",
                          "organization": "Lomedia",
                          "avatar": null,
                          "roleId": "742eaeac-1de0-4a50-a337-e75326ceb502",
                          "password": "$2b$10$1vmxBab3S0WZZ4Aw3kcSxeyOg6lAsKg1dRVvLrdREy.gzfpR6v.vS",
                          "isActive": false,
                          "customValues": {
                            "unit": 34,
                            "salary": 30000,
                            "born-date": "2025-10-12",
                            "select-this": "Siomay"
                          },
                          "createdAt": "2026-01-07T05:44:41.836Z",
                          "updatedAt": "2026-01-07T05:44:41.836Z",
                          "isJoined": true
                        },
                        {
                          "id": "e9826307-afe5-42be-ae2a-866489ba95c5",
                          "firstName": "Test",
                          "lastName": "Jaya",
                          "email": "testaja@mail.com",
                          "phone": "98782937",
                          "language": "no",
                          "organization": "Lomedia",
                          "avatar": null,
                          "roleId": "742eaeac-1de0-4a50-a337-e75326ceb502",
                          "password": "$2b$10$BL.FmTuct8CRtMdS3brj2uaUeSpjjEA2pt4mNxRepXbilwx9xy7YS",
                          "isActive": false,
                          "customValues": {
                            "unit": 34,
                            "salary": 30000,
                            "born-date": "2025-10-12",
                            "select-this": "Baso"
                          },
                          "createdAt": "2026-01-07T05:29:13.156Z",
                          "updatedAt": "2026-01-07T05:29:13.156Z",
                          "isJoined": true
                        },
                        {
                          "id": "89d444d0-d7e7-44a9-9d0d-2289f47a4bae",
                          "firstName": "Test",
                          "lastName": "Jaya",
                          "email": "test@mail.com",
                          "phone": "98782937",
                          "language": "no",
                          "organization": "Lomedia",
                          "avatar": null,
                          "roleId": "742eaeac-1de0-4a50-a337-e75326ceb502",
                          "password": "$2b$10$HPLneRACKasEBkSgxE/Ga.A1xpKPjd8VtR92m18e695LLzvs/n1Ju",
                          "isActive": false,
                          "customValues": {},
                          "createdAt": "2026-01-06T07:51:34.747Z",
                          "updatedAt": "2026-01-06T07:51:34.747Z",
                          "isJoined": false
                        }
                      ]
                    }
                  },
                  "6": {
                    "summary": "Success",
                    "value": {
                      "message": "Group deleted successfully"
                    }
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/groups/{id}/users": {
      "post": {
        "summary": "Insert Users",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "example": "aa0b1a79-a196-4240-8b29-fc3c5c0bcbdf",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer {{token}}",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "userIds": [
                  "b1dc2f22-4e4a-49fe-bfec-9607f5a00e76",
                  "e9826307-afe5-42be-ae2a-866489ba95c5"
                ]
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "1": {
                    "summary": "Bad Request",
                    "value": {
                      "statusCode": 400,
                      "message": "Validation failed"
                    }
                  },
                  "2": {
                    "summary": "Success",
                    "value": {
                      "message": "Group created successfully",
                      "group": {
                        "name": "Group 1",
                        "description": "This is test groups",
                        "id": "aa0b1a79-a196-4240-8b29-fc3c5c0bcbdf",
                        "createdAt": "2026-01-07T08:46:10.704Z",
                        "updatedAt": "2026-01-07T08:46:10.704Z",
                        "totalMembers": 0
                      }
                    }
                  },
                  "3": {
                    "summary": "Success",
                    "value": {
                      "id": "aa0b1a79-a196-4240-8b29-fc3c5c0bcbdf",
                      "name": "Group 1",
                      "description": "This is test groups",
                      "createdAt": "2026-01-07T08:46:10.704Z",
                      "updatedAt": "2026-01-07T08:46:10.704Z",
                      "totalMembers": 0,
                      "users": []
                    }
                  },
                  "4": {
                    "summary": "Success",
                    "value": {
                      "message": "Users added to group",
                      "group": {
                        "id": "aa0b1a79-a196-4240-8b29-fc3c5c0bcbdf",
                        "name": "Group 1",
                        "description": "This is test groups",
                        "createdAt": "2026-01-07T08:46:10.704Z",
                        "updatedAt": "2026-01-07T08:46:10.704Z",
                        "totalMembers": 2,
                        "users": [
                          {
                            "id": "e9826307-afe5-42be-ae2a-866489ba95c5",
                            "firstName": "Test",
                            "lastName": "Jaya",
                            "email": "testaja@mail.com",
                            "phone": "98782937",
                            "language": "no",
                            "organization": "Lomedia",
                            "avatar": null,
                            "roleId": "742eaeac-1de0-4a50-a337-e75326ceb502",
                            "isActive": false,
                            "customValues": {
                              "unit": 34,
                              "salary": 30000,
                              "born-date": "2025-10-12",
                              "select-this": "Baso"
                            },
                            "createdAt": "2026-01-07T05:29:13.156Z",
                            "updatedAt": "2026-01-07T05:29:13.156Z"
                          },
                          {
                            "id": "b1dc2f22-4e4a-49fe-bfec-9607f5a00e76",
                            "firstName": "Test aja ges",
                            "lastName": "Jaya ad",
                            "email": "testaja2@mail.com",
                            "phone": "98782937",
                            "language": "no",
                            "organization": "Lomedia",
                            "avatar": null,
                            "roleId": "742eaeac-1de0-4a50-a337-e75326ceb502",
                            "isActive": false,
                            "customValues": {
                              "unit": 34,
                              "salary": 30000,
                              "born-date": "2025-10-12",
                              "select-this": "Siomay"
                            },
                            "createdAt": "2026-01-07T05:44:41.836Z",
                            "updatedAt": "2026-01-07T05:44:41.836Z"
                          }
                        ]
                      }
                    }
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "get": {
        "summary": "Search Users",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "example": "aa0b1a79-a196-4240-8b29-fc3c5c0bcbdf",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "keywords",
            "in": "query",
            "description": "",
            "required": false,
            "example": "test",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer {{token}}",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": ""
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "1": {
                    "summary": "Bad Request",
                    "value": {
                      "statusCode": 400,
                      "message": "Validation failed"
                    }
                  },
                  "2": {
                    "summary": "Success",
                    "value": {
                      "message": "Group created successfully",
                      "group": {
                        "name": "Group 1",
                        "description": "This is test groups",
                        "id": "aa0b1a79-a196-4240-8b29-fc3c5c0bcbdf",
                        "createdAt": "2026-01-07T08:46:10.704Z",
                        "updatedAt": "2026-01-07T08:46:10.704Z",
                        "totalMembers": 0
                      }
                    }
                  },
                  "3": {
                    "summary": "Success",
                    "value": {
                      "id": "aa0b1a79-a196-4240-8b29-fc3c5c0bcbdf",
                      "name": "Group 1",
                      "description": "This is test groups",
                      "createdAt": "2026-01-07T08:46:10.704Z",
                      "updatedAt": "2026-01-07T08:46:10.704Z",
                      "totalMembers": 0,
                      "users": []
                    }
                  },
                  "4": {
                    "summary": "Success",
                    "value": {
                      "message": "Users added to group",
                      "group": {
                        "id": "aa0b1a79-a196-4240-8b29-fc3c5c0bcbdf",
                        "name": "Group 1",
                        "description": "This is test groups",
                        "createdAt": "2026-01-07T08:46:10.704Z",
                        "updatedAt": "2026-01-07T08:46:10.704Z",
                        "totalMembers": 2,
                        "users": [
                          {
                            "id": "e9826307-afe5-42be-ae2a-866489ba95c5",
                            "firstName": "Test",
                            "lastName": "Jaya",
                            "email": "testaja@mail.com",
                            "phone": "98782937",
                            "language": "no",
                            "organization": "Lomedia",
                            "avatar": null,
                            "roleId": "742eaeac-1de0-4a50-a337-e75326ceb502",
                            "isActive": false,
                            "customValues": {
                              "unit": 34,
                              "salary": 30000,
                              "born-date": "2025-10-12",
                              "select-this": "Baso"
                            },
                            "createdAt": "2026-01-07T05:29:13.156Z",
                            "updatedAt": "2026-01-07T05:29:13.156Z"
                          },
                          {
                            "id": "b1dc2f22-4e4a-49fe-bfec-9607f5a00e76",
                            "firstName": "Test aja ges",
                            "lastName": "Jaya ad",
                            "email": "testaja2@mail.com",
                            "phone": "98782937",
                            "language": "no",
                            "organization": "Lomedia",
                            "avatar": null,
                            "roleId": "742eaeac-1de0-4a50-a337-e75326ceb502",
                            "isActive": false,
                            "customValues": {
                              "unit": 34,
                              "salary": 30000,
                              "born-date": "2025-10-12",
                              "select-this": "Siomay"
                            },
                            "createdAt": "2026-01-07T05:44:41.836Z",
                            "updatedAt": "2026-01-07T05:44:41.836Z"
                          }
                        ]
                      }
                    }
                  },
                  "5": {
                    "summary": "Success",
                    "value": {
                      "groupId": "aa0b1a79-a196-4240-8b29-fc3c5c0bcbdf",
                      "totalMembers": 2,
                      "matched": 3,
                      "users": [
                        {
                          "id": "b1dc2f22-4e4a-49fe-bfec-9607f5a00e76",
                          "firstName": "Test aja ges",
                          "lastName": "Jaya ad",
                          "email": "testaja2@mail.com",
                          "phone": "98782937",
                          "language": "no",
                          "organization": "Lomedia",
                          "avatar": null,
                          "roleId": "742eaeac-1de0-4a50-a337-e75326ceb502",
                          "password": "$2b$10$1vmxBab3S0WZZ4Aw3kcSxeyOg6lAsKg1dRVvLrdREy.gzfpR6v.vS",
                          "isActive": false,
                          "customValues": {
                            "unit": 34,
                            "salary": 30000,
                            "born-date": "2025-10-12",
                            "select-this": "Siomay"
                          },
                          "createdAt": "2026-01-07T05:44:41.836Z",
                          "updatedAt": "2026-01-07T05:44:41.836Z",
                          "isJoined": true
                        },
                        {
                          "id": "e9826307-afe5-42be-ae2a-866489ba95c5",
                          "firstName": "Test",
                          "lastName": "Jaya",
                          "email": "testaja@mail.com",
                          "phone": "98782937",
                          "language": "no",
                          "organization": "Lomedia",
                          "avatar": null,
                          "roleId": "742eaeac-1de0-4a50-a337-e75326ceb502",
                          "password": "$2b$10$BL.FmTuct8CRtMdS3brj2uaUeSpjjEA2pt4mNxRepXbilwx9xy7YS",
                          "isActive": false,
                          "customValues": {
                            "unit": 34,
                            "salary": 30000,
                            "born-date": "2025-10-12",
                            "select-this": "Baso"
                          },
                          "createdAt": "2026-01-07T05:29:13.156Z",
                          "updatedAt": "2026-01-07T05:29:13.156Z",
                          "isJoined": true
                        },
                        {
                          "id": "89d444d0-d7e7-44a9-9d0d-2289f47a4bae",
                          "firstName": "Test",
                          "lastName": "Jaya",
                          "email": "test@mail.com",
                          "phone": "98782937",
                          "language": "no",
                          "organization": "Lomedia",
                          "avatar": null,
                          "roleId": "742eaeac-1de0-4a50-a337-e75326ceb502",
                          "password": "$2b$10$HPLneRACKasEBkSgxE/Ga.A1xpKPjd8VtR92m18e695LLzvs/n1Ju",
                          "isActive": false,
                          "customValues": {},
                          "createdAt": "2026-01-06T07:51:34.747Z",
                          "updatedAt": "2026-01-06T07:51:34.747Z",
                          "isJoined": false
                        }
                      ]
                    }
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "delete": {
        "summary": "Delete Users",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "example": "aa0b1a79-a196-4240-8b29-fc3c5c0bcbdf",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer {{token}}",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "userIds": [
                  "e9826307-afe5-42be-ae2a-866489ba95c5"
                ]
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "1": {
                    "summary": "Bad Request",
                    "value": {
                      "statusCode": 400,
                      "message": "Validation failed"
                    }
                  },
                  "2": {
                    "summary": "Success",
                    "value": {
                      "message": "Group created successfully",
                      "group": {
                        "name": "Group 1",
                        "description": "This is test groups",
                        "id": "aa0b1a79-a196-4240-8b29-fc3c5c0bcbdf",
                        "createdAt": "2026-01-07T08:46:10.704Z",
                        "updatedAt": "2026-01-07T08:46:10.704Z",
                        "totalMembers": 0
                      }
                    }
                  },
                  "3": {
                    "summary": "Success",
                    "value": {
                      "id": "aa0b1a79-a196-4240-8b29-fc3c5c0bcbdf",
                      "name": "Group 1",
                      "description": "This is test groups",
                      "createdAt": "2026-01-07T08:46:10.704Z",
                      "updatedAt": "2026-01-07T08:46:10.704Z",
                      "totalMembers": 0,
                      "users": []
                    }
                  },
                  "4": {
                    "summary": "Success",
                    "value": {
                      "message": "Users added to group",
                      "group": {
                        "id": "aa0b1a79-a196-4240-8b29-fc3c5c0bcbdf",
                        "name": "Group 1",
                        "description": "This is test groups",
                        "createdAt": "2026-01-07T08:46:10.704Z",
                        "updatedAt": "2026-01-07T08:46:10.704Z",
                        "totalMembers": 2,
                        "users": [
                          {
                            "id": "e9826307-afe5-42be-ae2a-866489ba95c5",
                            "firstName": "Test",
                            "lastName": "Jaya",
                            "email": "testaja@mail.com",
                            "phone": "98782937",
                            "language": "no",
                            "organization": "Lomedia",
                            "avatar": null,
                            "roleId": "742eaeac-1de0-4a50-a337-e75326ceb502",
                            "isActive": false,
                            "customValues": {
                              "unit": 34,
                              "salary": 30000,
                              "born-date": "2025-10-12",
                              "select-this": "Baso"
                            },
                            "createdAt": "2026-01-07T05:29:13.156Z",
                            "updatedAt": "2026-01-07T05:29:13.156Z"
                          },
                          {
                            "id": "b1dc2f22-4e4a-49fe-bfec-9607f5a00e76",
                            "firstName": "Test aja ges",
                            "lastName": "Jaya ad",
                            "email": "testaja2@mail.com",
                            "phone": "98782937",
                            "language": "no",
                            "organization": "Lomedia",
                            "avatar": null,
                            "roleId": "742eaeac-1de0-4a50-a337-e75326ceb502",
                            "isActive": false,
                            "customValues": {
                              "unit": 34,
                              "salary": 30000,
                              "born-date": "2025-10-12",
                              "select-this": "Siomay"
                            },
                            "createdAt": "2026-01-07T05:44:41.836Z",
                            "updatedAt": "2026-01-07T05:44:41.836Z"
                          }
                        ]
                      }
                    }
                  },
                  "5": {
                    "summary": "Success",
                    "value": {
                      "groupId": "aa0b1a79-a196-4240-8b29-fc3c5c0bcbdf",
                      "totalMembers": 2,
                      "matched": 3,
                      "users": [
                        {
                          "id": "b1dc2f22-4e4a-49fe-bfec-9607f5a00e76",
                          "firstName": "Test aja ges",
                          "lastName": "Jaya ad",
                          "email": "testaja2@mail.com",
                          "phone": "98782937",
                          "language": "no",
                          "organization": "Lomedia",
                          "avatar": null,
                          "roleId": "742eaeac-1de0-4a50-a337-e75326ceb502",
                          "password": "$2b$10$1vmxBab3S0WZZ4Aw3kcSxeyOg6lAsKg1dRVvLrdREy.gzfpR6v.vS",
                          "isActive": false,
                          "customValues": {
                            "unit": 34,
                            "salary": 30000,
                            "born-date": "2025-10-12",
                            "select-this": "Siomay"
                          },
                          "createdAt": "2026-01-07T05:44:41.836Z",
                          "updatedAt": "2026-01-07T05:44:41.836Z",
                          "isJoined": true
                        },
                        {
                          "id": "e9826307-afe5-42be-ae2a-866489ba95c5",
                          "firstName": "Test",
                          "lastName": "Jaya",
                          "email": "testaja@mail.com",
                          "phone": "98782937",
                          "language": "no",
                          "organization": "Lomedia",
                          "avatar": null,
                          "roleId": "742eaeac-1de0-4a50-a337-e75326ceb502",
                          "password": "$2b$10$BL.FmTuct8CRtMdS3brj2uaUeSpjjEA2pt4mNxRepXbilwx9xy7YS",
                          "isActive": false,
                          "customValues": {
                            "unit": 34,
                            "salary": 30000,
                            "born-date": "2025-10-12",
                            "select-this": "Baso"
                          },
                          "createdAt": "2026-01-07T05:29:13.156Z",
                          "updatedAt": "2026-01-07T05:29:13.156Z",
                          "isJoined": true
                        },
                        {
                          "id": "89d444d0-d7e7-44a9-9d0d-2289f47a4bae",
                          "firstName": "Test",
                          "lastName": "Jaya",
                          "email": "test@mail.com",
                          "phone": "98782937",
                          "language": "no",
                          "organization": "Lomedia",
                          "avatar": null,
                          "roleId": "742eaeac-1de0-4a50-a337-e75326ceb502",
                          "password": "$2b$10$HPLneRACKasEBkSgxE/Ga.A1xpKPjd8VtR92m18e695LLzvs/n1Ju",
                          "isActive": false,
                          "customValues": {},
                          "createdAt": "2026-01-06T07:51:34.747Z",
                          "updatedAt": "2026-01-06T07:51:34.747Z",
                          "isJoined": false
                        }
                      ]
                    }
                  },
                  "6": {
                    "summary": "Success",
                    "value": {
                      "message": "Group deleted successfully"
                    }
                  },
                  "7": {
                    "summary": "Success",
                    "value": {
                      "message": "Users removed from group",
                      "group": {
                        "id": "aa0b1a79-a196-4240-8b29-fc3c5c0bcbdf",
                        "name": "Modify",
                        "description": "",
                        "createdAt": "2026-01-07T08:46:10.704Z",
                        "updatedAt": "2026-01-07T09:12:11.112Z",
                        "totalMembers": 1,
                        "users": [
                          {
                            "id": "b1dc2f22-4e4a-49fe-bfec-9607f5a00e76",
                            "firstName": "Test aja ges",
                            "lastName": "Jaya ad",
                            "email": "testaja2@mail.com",
                            "phone": "98782937",
                            "language": "no",
                            "organization": "Lomedia",
                            "avatar": null,
                            "roleId": "742eaeac-1de0-4a50-a337-e75326ceb502",
                            "isActive": false,
                            "customValues": {
                              "unit": 34,
                              "salary": 30000,
                              "born-date": "2025-10-12",
                              "select-this": "Siomay"
                            },
                            "createdAt": "2026-01-07T05:44:41.836Z",
                            "updatedAt": "2026-01-07T05:44:41.836Z"
                          }
                        ]
                      }
                    }
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    }
  },
  "components": {
    "schemas": {},
    "responses": {},
    "securitySchemes": {}
  },
  "servers": [],
  "security": []
}